; PlatformIO Project Configuration File
;
; LED Pong - ESP32 + WS2812B (NeoPixelBus)
;
[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    makuna/NeoPixelBus@^2.7.9
monitor_speed = 115200
